name: serendipia
description: Simple RESTful (Representational State Transfer) gateway service for the purpose of discovery, load balancing and failover.
version: 1.0.0
homepage: https://github.com/ushieru/serendipia

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  dart_jsonwebtoken: ^2.4.1
  http: ^0.13.4
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  version: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
